/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectAkhir;

import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class HiPiC extends javax.swing.JFrame {

    String bil;
    String a = new String ("ERROR");
    double cal, bil1, bil2,mj,k,p,g,u,t,d,m;
    int select;

    /**
     * Creates new form NewJFrame
     */
    public HiPiC() {
        initComponents();
        this.setTitle("Hi PiC(Physic Calculator)");
        this.setLocationRelativeTo(this);
        ImageIcon icon = new ImageIcon("src/projectAkhir/icon.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jP_massajenis = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mj1 = new javax.swing.JTextField();
        mj2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jL_mj = new javax.swing.JLabel();
        jP_kecepatan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        k2 = new javax.swing.JTextField();
        k1 = new javax.swing.JTextField();
        jL_k = new javax.swing.JLabel();
        jP_percepatan = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        jL_p = new javax.swing.JLabel();
        jP_gaya = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        g2 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        jL_g = new javax.swing.JLabel();
        jP_usaha = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        u2 = new javax.swing.JTextField();
        u1 = new javax.swing.JTextField();
        jL_u = new javax.swing.JLabel();
        jP_tekanan = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jL_t = new javax.swing.JLabel();
        jP_daya = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        jL_d = new javax.swing.JLabel();
        jP_momentum = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        m2 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        jL_m = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jL_IO = new javax.swing.JLabel();
        jB_sin = new javax.swing.JButton();
        jB_log = new javax.swing.JButton();
        jB_akar = new javax.swing.JButton();
        jB_kali = new javax.swing.JButton();
        jB_cos = new javax.swing.JButton();
        jB_mod = new javax.swing.JButton();
        jB_faktorial = new javax.swing.JButton();
        jB_bagi = new javax.swing.JButton();
        jB_tan = new javax.swing.JButton();
        jB_exp = new javax.swing.JButton();
        jB_plusmin = new javax.swing.JButton();
        jB_jumlah = new javax.swing.JButton();
        jB_delete = new javax.swing.JButton();
        jB_pangkat = new javax.swing.JButton();
        jB_koma = new javax.swing.JButton();
        jB_clear = new javax.swing.JButton();
        jB_equals = new javax.swing.JButton();
        jB_kurang = new javax.swing.JButton();
        jB_7 = new javax.swing.JButton();
        jB_8 = new javax.swing.JButton();
        jB_9 = new javax.swing.JButton();
        jB_6 = new javax.swing.JButton();
        jB_5 = new javax.swing.JButton();
        jB_4 = new javax.swing.JButton();
        jB_3 = new javax.swing.JButton();
        jB_1 = new javax.swing.JButton();
        jB_2 = new javax.swing.JButton();
        jB_0 = new javax.swing.JButton();
        jB_hitung = new javax.swing.JButton();
        jB_bersih = new javax.swing.JButton();
        jB_ln = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("Hasil :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 120));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(378, 188));

        jP_massajenis.setBackground(new java.awt.Color(51, 51, 51));
        jP_massajenis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_massajenis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Massa Jenis (ρ)  = Massa (m) : Volume (V)");
        jP_massajenis.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("=              Kg :             m");
        jP_massajenis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 20));

        mj1.setForeground(new java.awt.Color(255, 153, 0));
        jP_massajenis.add(mj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, -1));

        mj2.setForeground(new java.awt.Color(255, 153, 0));
        jP_massajenis.add(mj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 40, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("3");
        jP_massajenis.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 30, -1));

        jL_mj.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_mj.setForeground(new java.awt.Color(255, 153, 0));
        jP_massajenis.add(jL_mj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Massa Jenis", jP_massajenis);

        jP_kecepatan.setBackground(new java.awt.Color(51, 51, 51));
        jP_kecepatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_kecepatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kecepatan (v)   =    Jarak (S)  :  Waktu (t)");
        jP_kecepatan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 240, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("=              m  :              s");
        jP_kecepatan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 20));

        k2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        k2.setForeground(new java.awt.Color(255, 153, 0));
        jP_kecepatan.add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, -1));

        k1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        k1.setForeground(new java.awt.Color(255, 153, 0));
        jP_kecepatan.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 40, -1));

        jL_k.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_k.setForeground(new java.awt.Color(255, 153, 0));
        jP_kecepatan.add(jL_k, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 40));

        jTabbedPane1.addTab("Kecepatan", jP_kecepatan);

        jP_percepatan.setBackground(new java.awt.Color(51, 51, 51));
        jP_percepatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_percepatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("percepatan (α)  =      (v2-v1)      :     selang waktu");
        jP_percepatan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("=        Δv           :     Δt");
        jP_percepatan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("=                m/s :              s");
        jP_percepatan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 20));

        p2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 153, 0));
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jP_percepatan.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, -1));

        p1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 153, 0));
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jP_percepatan.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, -1));

        jL_p.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_p.setForeground(new java.awt.Color(255, 153, 0));
        jP_percepatan.add(jL_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Percepatan", jP_percepatan);

        jP_gaya.setBackground(new java.awt.Color(51, 51, 51));
        jP_gaya.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_gaya.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("gaya (F)  =  Massa (m) x percepatan (α)");
        jP_gaya.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(" =             Kg  x             m/s ");
        jP_gaya.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("  2");
        jP_gaya.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 30, -1));

        g2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        g2.setForeground(new java.awt.Color(255, 153, 0));
        jP_gaya.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 40, -1));

        g1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        g1.setForeground(new java.awt.Color(255, 153, 0));
        jP_gaya.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 40, -1));

        jL_g.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_g.setForeground(new java.awt.Color(255, 153, 0));
        jP_gaya.add(jL_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Gaya", jP_gaya);

        jP_usaha.setBackground(new java.awt.Color(51, 51, 51));
        jP_usaha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_usaha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("W   =    gaya (F)     x    Jarak Perpindahan (S)");
        jP_usaha.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 270, -1));

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(" =                N  x               m");
        jP_usaha.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        u2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        u2.setForeground(new java.awt.Color(255, 153, 0));
        u2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u2ActionPerformed(evt);
            }
        });
        jP_usaha.add(u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 40, -1));

        u1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        u1.setForeground(new java.awt.Color(255, 153, 0));
        jP_usaha.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 40, -1));

        jL_u.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_u.setForeground(new java.awt.Color(255, 153, 0));
        jP_usaha.add(jL_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Usaha & energi", jP_usaha);

        jP_tekanan.setBackground(new java.awt.Color(51, 51, 51));
        jP_tekanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_tekanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tekanan (P)   =    gaya (F)    :    Luas (A)");
        jP_tekanan.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 260, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("=               N  :              m  ");
        jP_tekanan.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 20));

        t2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 153, 0));
        jP_tekanan.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 40, -1));

        t1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 153, 0));
        jP_tekanan.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("  2");
        jP_tekanan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 30, -1));

        jL_t.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_t.setForeground(new java.awt.Color(255, 153, 0));
        jP_tekanan.add(jL_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Tekanan", jP_tekanan);

        jP_daya.setBackground(new java.awt.Color(51, 51, 51));
        jP_daya.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_daya.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Daya (P)   =  Energi (W)  :  Selang waktu (Δt)");
        jP_daya.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 27, 270, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("=                J   :            s");
        jP_daya.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, 20));

        d2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        d2.setForeground(new java.awt.Color(255, 153, 0));
        jP_daya.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 40, -1));

        d1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 153, 0));
        jP_daya.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, -1));

        jL_d.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_d.setForeground(new java.awt.Color(255, 153, 0));
        jP_daya.add(jL_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Daya", jP_daya);

        jP_momentum.setBackground(new java.awt.Color(51, 51, 51));
        jP_momentum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jP_momentum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Momentum (P)  =  Massa (m)    :  kecepatan (v)");
        jP_momentum.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("=              Kg  :              m/s");
        jP_momentum.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 20));

        m2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 153, 0));
        jP_momentum.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, -1));

        m1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 153, 0));
        jP_momentum.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 40, -1));

        jL_m.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_m.setForeground(new java.awt.Color(255, 153, 0));
        jP_momentum.add(jL_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        jTabbedPane1.addTab("Momentum", jP_momentum);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 190));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_IO.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jPanel7.add(jL_IO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 360, 70));

        jB_sin.setBackground(new java.awt.Color(102, 102, 102));
        jB_sin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_sin.setForeground(new java.awt.Color(255, 255, 255));
        jB_sin.setText("sin");
        jB_sin.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sinActionPerformed(evt);
            }
        });
        getContentPane().add(jB_sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jB_log.setBackground(new java.awt.Color(102, 102, 102));
        jB_log.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_log.setForeground(new java.awt.Color(255, 255, 255));
        jB_log.setText("log");
        jB_log.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logActionPerformed(evt);
            }
        });
        getContentPane().add(jB_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jB_akar.setBackground(new java.awt.Color(102, 102, 102));
        jB_akar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_akar.setForeground(new java.awt.Color(255, 255, 255));
        jB_akar.setText("√");
        jB_akar.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_akarActionPerformed(evt);
            }
        });
        getContentPane().add(jB_akar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jB_kali.setBackground(new java.awt.Color(255, 255, 255));
        jB_kali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_kali.setText("x");
        jB_kali.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kaliActionPerformed(evt);
            }
        });
        getContentPane().add(jB_kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 50, -1));

        jB_cos.setBackground(new java.awt.Color(102, 102, 102));
        jB_cos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_cos.setForeground(new java.awt.Color(255, 255, 255));
        jB_cos.setText("cos");
        jB_cos.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cosActionPerformed(evt);
            }
        });
        getContentPane().add(jB_cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jB_mod.setBackground(new java.awt.Color(102, 102, 102));
        jB_mod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_mod.setForeground(new java.awt.Color(255, 255, 255));
        jB_mod.setText("%");
        jB_mod.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_modActionPerformed(evt);
            }
        });
        getContentPane().add(jB_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        jB_faktorial.setBackground(new java.awt.Color(102, 102, 102));
        jB_faktorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_faktorial.setForeground(new java.awt.Color(255, 255, 255));
        jB_faktorial.setText("n!");
        jB_faktorial.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_faktorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_faktorialActionPerformed(evt);
            }
        });
        getContentPane().add(jB_faktorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jB_bagi.setBackground(new java.awt.Color(255, 255, 255));
        jB_bagi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_bagi.setText("÷");
        jB_bagi.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_bagiActionPerformed(evt);
            }
        });
        getContentPane().add(jB_bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 50, -1));

        jB_tan.setBackground(new java.awt.Color(102, 102, 102));
        jB_tan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_tan.setForeground(new java.awt.Color(255, 255, 255));
        jB_tan.setText("tan");
        jB_tan.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_tanActionPerformed(evt);
            }
        });
        getContentPane().add(jB_tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 50, -1));

        jB_exp.setBackground(new java.awt.Color(102, 102, 102));
        jB_exp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_exp.setForeground(new java.awt.Color(255, 255, 255));
        jB_exp.setText("exp");
        jB_exp.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_expActionPerformed(evt);
            }
        });
        getContentPane().add(jB_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jB_plusmin.setBackground(new java.awt.Color(102, 102, 102));
        jB_plusmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_plusmin.setForeground(new java.awt.Color(255, 255, 255));
        jB_plusmin.setText("+/-");
        jB_plusmin.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_plusmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_plusminActionPerformed(evt);
            }
        });
        getContentPane().add(jB_plusmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jB_jumlah.setBackground(new java.awt.Color(255, 255, 255));
        jB_jumlah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_jumlah.setText("+");
        jB_jumlah.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jB_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jB_delete.setBackground(new java.awt.Color(255, 153, 0));
        jB_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_delete.setForeground(new java.awt.Color(255, 255, 255));
        jB_delete.setText("DEL");
        jB_delete.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jB_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, -1));

        jB_pangkat.setBackground(new java.awt.Color(102, 102, 102));
        jB_pangkat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_pangkat.setForeground(new java.awt.Color(255, 255, 255));
        jB_pangkat.setText("x^");
        jB_pangkat.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(jB_pangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 50, -1));

        jB_koma.setBackground(new java.awt.Color(255, 255, 255));
        jB_koma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_koma.setText(".");
        jB_koma.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_komaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 50, -1));

        jB_clear.setBackground(new java.awt.Color(255, 153, 0));
        jB_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_clear.setForeground(new java.awt.Color(255, 255, 255));
        jB_clear.setText("C");
        jB_clear.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jB_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 40, -1));

        jB_equals.setBackground(new java.awt.Color(255, 153, 0));
        jB_equals.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_equals.setForeground(new java.awt.Color(255, 255, 255));
        jB_equals.setText("=");
        jB_equals.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_equalsActionPerformed(evt);
            }
        });
        getContentPane().add(jB_equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 70, -1));

        jB_kurang.setBackground(new java.awt.Color(255, 255, 255));
        jB_kurang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_kurang.setText("-");
        jB_kurang.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_kurangActionPerformed(evt);
            }
        });
        getContentPane().add(jB_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        jB_7.setBackground(new java.awt.Color(255, 255, 255));
        jB_7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_7.setText("7");
        jB_7.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jB_8.setBackground(new java.awt.Color(255, 255, 255));
        jB_8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_8.setText("8");
        jB_8.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 50, -1));

        jB_9.setBackground(new java.awt.Color(255, 255, 255));
        jB_9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_9.setText("9");
        jB_9.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jB_6.setBackground(new java.awt.Color(255, 255, 255));
        jB_6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_6.setText("6");
        jB_6.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jB_5.setBackground(new java.awt.Color(255, 255, 255));
        jB_5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_5.setText("5");
        jB_5.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jB_4.setBackground(new java.awt.Color(255, 255, 255));
        jB_4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_4.setText("4");
        jB_4.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jB_3.setBackground(new java.awt.Color(255, 255, 255));
        jB_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_3.setText("3");
        jB_3.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        jB_1.setBackground(new java.awt.Color(255, 255, 255));
        jB_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_1.setText("1");
        jB_1.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jB_2.setBackground(new java.awt.Color(255, 255, 255));
        jB_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_2.setText("2");
        jB_2.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jB_0.setBackground(new java.awt.Color(255, 255, 255));
        jB_0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jB_0.setText("0");
        jB_0.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 80, -1));

        jB_hitung.setBackground(new java.awt.Color(255, 153, 0));
        jB_hitung.setFont(new java.awt.Font("Tekton Pro Ext", 3, 14)); // NOI18N
        jB_hitung.setForeground(new java.awt.Color(255, 255, 255));
        jB_hitung.setText("Count");
        jB_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_hitungActionPerformed(evt);
            }
        });
        getContentPane().add(jB_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, 30));

        jB_bersih.setBackground(new java.awt.Color(255, 153, 0));
        jB_bersih.setFont(new java.awt.Font("Tekton Pro Ext", 3, 14)); // NOI18N
        jB_bersih.setForeground(new java.awt.Color(255, 255, 255));
        jB_bersih.setText("Clear");
        jB_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_bersihActionPerformed(evt);
            }
        });
        getContentPane().add(jB_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        jB_ln.setBackground(new java.awt.Color(102, 102, 102));
        jB_ln.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_ln.setForeground(new java.awt.Color(255, 255, 255));
        jB_ln.setText("ln");
        jB_ln.setPreferredSize(new java.awt.Dimension(50, 30));
        jB_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_lnActionPerformed(evt);
            }
        });
        getContentPane().add(jB_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectAkhir/icon.png"))); // NOI18N
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 60, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jLabel2.setText("by H!gh copyright 2020 / 1955201011-ILKOM_2A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 380, 20));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectAkhir/images (8).jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 380, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_deleteActionPerformed
        // TODO add your handling code here:
        jL_IO.setText(bil.substring(0, jL_IO.getText().length() - 1));
    }//GEN-LAST:event_jB_deleteActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void u2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u2ActionPerformed

    private void jB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 0;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_0ActionPerformed

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 1;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 2;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 3;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 4;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 5;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 6;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 7;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 8;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + 9;
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_9ActionPerformed

    private void jB_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_clearActionPerformed
        // TODO add your handling code here:
        jL_IO.setText("");
    }//GEN-LAST:event_jB_clearActionPerformed

    private void jB_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_jumlahActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " + ";
        jL_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_jumlahActionPerformed

    private void jB_komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_komaActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + ".";
        jL_IO.setText(bil);
    }//GEN-LAST:event_jB_komaActionPerformed

    private void jB_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kaliActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " x ";
        jL_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_kaliActionPerformed

    private void jB_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_kurangActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " - ";
        jL_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_kurangActionPerformed

    private void jB_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_bagiActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " ÷ ";
        jL_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_bagiActionPerformed

    private void jB_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "log ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_logActionPerformed

    private void jB_akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_akarActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "√ ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_akarActionPerformed

    private void jB_pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_pangkatActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " ^ ";
        jL_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_pangkatActionPerformed

    private void jB_plusminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_plusminActionPerformed
        // TODO add your handling code here:
        Double x = Double.valueOf(jL_IO.getText());
        Double y = -1 * x;
        jL_IO.setText(String.valueOf(y));
    }//GEN-LAST:event_jB_plusminActionPerformed

    private void jB_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_modActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " % ";
        jL_IO.setText(bil);
        select = 1;
    }//GEN-LAST:event_jB_modActionPerformed

    private void jB_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_lnActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "ln ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_lnActionPerformed

    private void jB_faktorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_faktorialActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + " !";
        jL_IO.setText(bil);
        select = 3;
    }//GEN-LAST:event_jB_faktorialActionPerformed

    private void jB_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sinActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "sin ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_sinActionPerformed

    private void jB_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cosActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "cos ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_cosActionPerformed

    private void jB_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_tanActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "tan ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_tanActionPerformed

    private void jB_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_expActionPerformed
        // TODO add your handling code here:
        bil = jL_IO.getText() + "exp ";
        jL_IO.setText(bil);
        select = 2;
    }//GEN-LAST:event_jB_expActionPerformed

    private void jB_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_equalsActionPerformed
        switch (select){
            case 1:
                int x = jL_IO.getText().length();
                bil1= Double.parseDouble(bil.substring(0, bil.indexOf(" ")));
                bil2= Double.parseDouble(bil.substring(bil.indexOf(" ")+2,x));
                String pilih1= bil.substring(bil.indexOf(" ")+1, bil.indexOf(" ")+2);
                
                if(pilih1.equals("+")){
                    cal= bil1 + bil2;
                }
                else if (pilih1.equals("-")){
                    cal= bil1 - bil2;
                }
                else if (pilih1.equals("x")){
                    cal= bil1 * bil2;
                }
                else if (pilih1.equals("÷")){
                    cal= bil1 / bil2;
                }
                else if (pilih1.equals("%")){
                    cal= bil1 % bil2;
                }
                else if (pilih1.equals("^")){
                    cal= Math.pow(bil1,bil2);
                }
                
                break;
                
            case 2:
                int y = jL_IO.getText().length();
                bil2 = Double.parseDouble(bil.substring(bil.indexOf(" ") + 1, y));
                String pilih2 = bil.substring(0, bil.indexOf(" "));
                
                if (pilih2.equals("√")) {
                    cal = Math.sqrt(bil2);
                }
                else if (pilih2.equals("!")) {
                    for (int i = 1; i <= bil1; i++) {
                        cal = cal * i;
                    }
                }
                else if (pilih2.equals("log")) {
                    cal = Math.log10(bil2);
                }
                else if (pilih2.equals("sin")) {
                    cal = Math.sin(Math.toRadians(bil2));
                }
                else if (pilih2.equals("cos")) {
                    cal = Math.cos(Math.toRadians(bil2));
                }
                else if (pilih2.equals("tan")) {
                    cal = Math.tan(Math.toRadians(bil2));
                }
                else if(pilih2.equals("ln")){
                    cal = Math.log(bil2);
                }
                else if(pilih2.equals("exp")){
                    cal = Math.exp(bil2);
                }
               
                break;
                
            case 3:
                bil1 = Double.parseDouble(bil.substring(0, bil.indexOf(" ")));
                String pilih3 = bil.substring(bil.indexOf(" ") + 1, bil.indexOf(" ") + 2);

                if (pilih3.equals("!")) {
                    cal = 1;
                    for(double i=bil1; i>0; i--){
                        cal *= i;
                    }
                }
                break;
            default:
            a =("ERROR");
                
        }if (false){
        jL_IO.setText(a);}
        else if (true){
        jL_IO.setText(String.valueOf(cal));}
        
    }//GEN-LAST:event_jB_equalsActionPerformed

    private void jB_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_hitungActionPerformed

       if(jP_massajenis.isShowing()){
        double fmj[]= new double[2];
        fmj[0]= Double.parseDouble(mj1.getText());
        fmj[1]= Double.parseDouble(mj2.getText());
        mj= fmj[0]/fmj[1];
        jL_mj.setText(String.valueOf(mj)+" Kg/m^3");
       }
       
       else if(jP_kecepatan.isShowing()){
        double fk[]= new double[2];
        fk[0]= Double.parseDouble(k1.getText());
        fk[1]= Double.parseDouble(k2.getText());
        k= fk[0]/fk[1];
        jL_k.setText(String.valueOf(k)+" m/s");
       }
       
       else if(jP_percepatan.isShowing()){
        double fp[]= new double[2];
        fp[0]= Double.parseDouble(p1.getText());
        fp[1]= Double.parseDouble(p2.getText());
        p= fp[0]/fp[1];
        jL_p.setText(String.valueOf(p)+" m/s^2");
       }
       
       else if(jP_gaya.isShowing()){
        double fg[]= new double[2];
        fg[0]= Double.parseDouble(g1.getText());
        fg[1]= Double.parseDouble(g2.getText());
        g= fg[0]*fg[1];
        jL_g.setText(String.valueOf(g)+" N");
       }
       
       else if(jP_usaha.isShowing()){
        double fu[]= new double[2];
        fu[0]= Double.parseDouble(u1.getText());
        fu[1]= Double.parseDouble(u2.getText());
        u= fu[0]*fu[1];
        jL_u.setText(String.valueOf(u)+" J");
       }
       
       else if(jP_tekanan.isShowing()){
        double ft[]= new double[2];
        ft[0]= Double.parseDouble(t1.getText());
        ft[1]= Double.parseDouble(t2.getText());
        t= ft[0]/ft[1];
        jL_t.setText(String.valueOf(t)+" Pa");
       }
       
       else if(jP_daya.isShowing()){
        double fd[]= new double[2];
        fd[0]= Double.parseDouble(d1.getText());
        fd[1]= Double.parseDouble(d2.getText());
        d= fd[0]/fd[1];
        jL_d.setText(String.valueOf(d)+" Watt");
       }
       
       else if(jP_momentum.isShowing()){
        double fm[]= new double[2];
        fm[0]= Double.parseDouble(m1.getText());
        fm[1]= Double.parseDouble(m2.getText());
        m= fm[0]*fm[1];
        jL_m.setText(String.valueOf(m)+" Kg.m/s");
       }
    }//GEN-LAST:event_jB_hitungActionPerformed

    private void jB_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_bersihActionPerformed
        
        mj1.setText("");
        k1.setText("");
        p1.setText("");
        g1.setText("");
        u1.setText("");
        t1.setText("");
        d1.setText("");
        m1.setText("");
                       
        mj2.setText("");
        k2.setText("");
        p2.setText("");
        g2.setText("");
        u2.setText("");
        t2.setText("");
        d2.setText("");
        m2.setText("");
                          
        jL_mj.setText("");
        jL_k.setText(""); 
        jL_p.setText(""); 
        jL_g.setText(""); 
        jL_u.setText(""); 
        jL_t.setText(""); 
        jL_d.setText(""); 
        jL_m.setText("");
        
        
       
    }//GEN-LAST:event_jB_bersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HiPiC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HiPiC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HiPiC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HiPiC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HiPiC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JButton jB_0;
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_akar;
    private javax.swing.JButton jB_bagi;
    private javax.swing.JButton jB_bersih;
    private javax.swing.JButton jB_clear;
    private javax.swing.JButton jB_cos;
    private javax.swing.JButton jB_delete;
    private javax.swing.JButton jB_equals;
    private javax.swing.JButton jB_exp;
    private javax.swing.JButton jB_faktorial;
    private javax.swing.JButton jB_hitung;
    private javax.swing.JButton jB_jumlah;
    private javax.swing.JButton jB_kali;
    private javax.swing.JButton jB_koma;
    private javax.swing.JButton jB_kurang;
    private javax.swing.JButton jB_ln;
    private javax.swing.JButton jB_log;
    private javax.swing.JButton jB_mod;
    private javax.swing.JButton jB_pangkat;
    private javax.swing.JButton jB_plusmin;
    private javax.swing.JButton jB_sin;
    private javax.swing.JButton jB_tan;
    private javax.swing.JLabel jL_IO;
    private javax.swing.JLabel jL_d;
    private javax.swing.JLabel jL_g;
    private javax.swing.JLabel jL_k;
    private javax.swing.JLabel jL_m;
    private javax.swing.JLabel jL_mj;
    private javax.swing.JLabel jL_p;
    private javax.swing.JLabel jL_t;
    private javax.swing.JLabel jL_u;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jP_daya;
    private javax.swing.JPanel jP_gaya;
    private javax.swing.JPanel jP_kecepatan;
    private javax.swing.JPanel jP_massajenis;
    private javax.swing.JPanel jP_momentum;
    private javax.swing.JPanel jP_percepatan;
    private javax.swing.JPanel jP_tekanan;
    private javax.swing.JPanel jP_usaha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField k1;
    private javax.swing.JTextField k2;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField mj1;
    private javax.swing.JTextField mj2;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField u1;
    private javax.swing.JTextField u2;
    // End of variables declaration//GEN-END:variables
}
